car_search_project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('search_model/', views.search_model, name='search_model'),
    path('ajax/select_model/', views.select_model, name='ajax_select_model'),
]

car_search_project/models.py
from django.db import models


class Vehicle(models.Model):
	# id = models.IntegerField()
	make_id = models.IntegerField()
	make_desc = models.CharField(max_length=128)
	model_id = models.IntegerField()
	model_desc = models.CharField(max_length=128)
	variant_id = models.IntegerField()
	variant_desc = models.CharField(max_length=128)
	motor_flag = models.CharField(max_length=128)
	fuel_type_id = models.IntegerField()
	fuel_type_desc = models.CharField(max_length=128)
	seating_capacity = models.IntegerField()
	vehicle_image = models.CharField(max_length=128)
	search_string = models.CharField(max_length=128, db_index=True, unique=True)
	search_count = models.IntegerField(default=0, db_index=True)

	def __str__(self):
		return ("{} : {} ".format(self.search_string, self.search_count))

car_search_project/forms.py
from django import forms

class SearchForm(forms.Form):
	search_string = forms.CharField(max_length=128, label="Vehicle name")

car_search_project/views.py
import json
from django.http import HttpResponse, JsonResponse
from .forms import SearchForm
from .models import Vehicle
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST


@require_GET
def index(request):
	form = SearchForm()
	return render(request, 'index.html', {'form':form})

@require_GET
def search_model(request):
	search_string = request.GET.get('search_string')
	model_list = [d['search_string'] for d in Vehicle.objects.filter(search_string__icontains=search_string).order_by('-search_count').values("search_string")]
	return JsonResponse({"model_list": model_list})

@require_POST
def select_model(request):
	search_string = request.POST['search_string']
	vehicle = Vehicle.objects.get(search_string=search_string)
	if vehicle:
		vehicle.search_count += 1
		vehicle.save()
		return JsonResponse({'Message': 'Select count updated'})
	else :
		return JsonResponse({'Message': 'Invalid model'})
	

templates/index.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
	<title>Search Vehicle</title>

	<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script src="{% static 'js/car_search.js' %}"> </script>
	
	<style type="text/css">
		#id_search_string{
			width:400px;
		}
	</style>

	<script >
		var searchURL = "{% url 'search_model' %}";
		var selectURL = "{% url 'ajax_select_model' %}";
	</script>
</head>

<body>
	{{form.as_p}}
</body>
</html>